# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
customCommands:
  services:
    - name: bash
      attach: true
      command: "docker exec -it {{ .Container.ID }} bash"
    - name: zsh
      attach: true
      command: "docker exec -it {{ .Container.ID }} zsh"
