#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

PYTHONPATH="$BASEDIR/packages/dotbot_plugins" "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    --base-directory "${BASEDIR}" \
    --config-file "${CONFIG}" \
    --plugin plugins.py \
    --verbose \
    "${@}"
