#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

if command -v apt; then
    sudo apt update
    sudo apt install -y python3
fi

if [ -f "$HOME/.zshrc" ]; then
    rm "$HOME/.zshrc"
fi

DOTBOT_INSTALL_CONFIG="install-to-devcontainer.conf.yaml" "${BASEDIR}/install"
