[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
dotbot = "^1.20.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
