[tools]
atuin = "latest"
chezmoi = "latest"
claude-code = "latest"
eza = "latest"
gh = "latest"
go = "latest"
lazydocker = "latest"
neovim = "stable"
node = "latest"
usage = "latest"
zoxide = "latest"
