[tools]
# =========================
# 1. SHELL
# =========================

# --- Environment Manager ---
chezmoi = "latest"

# --- Utilities ---
atuin = "latest"
eza = "latest"
zoxide = "latest"

# =========================
# 2. CODING
# =========================

# --- Editors ---
helix = "latest"

# --- General ---
biome = "latest"

# --- Shell Script ---
"npm:bash-language-server" = "latest"

usage = "latest"

# --- Go ---
go = "latest"

"go:golang.org/x/tools/gopls" = "latest"

"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/mfridman/tparse" = "latest"

# --- Java Script/JSON & TypeScript ---
node = "latest"

pnpm = "latest"

"npm:vscode-json-languageserver" = "latest"
"npm:typescript-language-server" = "latest"

# --- Lua ---
lua-language-server = "latest"

stylua = "latest"

# --- Others ---
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"go:github.com/sqls-server/sqls" = "latest"
marksman = "latest"
tombi = "latest"

# =========================
# 3. DEVELOPMENT TOOLS
# =========================

# --- Documentation ---
"npm:ctx7" = "latest"

# --- Data & File Operations ---
resvg = "latest"
yazi = { version = "latest", postinstall = "ya pkg install" }

# --- Version Control & Diff Visualizer ---
gh = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"npm:difit" = "latest"

# --- Container ---
lazydocker = "latest"

# =========================
# 4. AI
# =========================

# --- Clients ---
claude-code = "latest"
codex = "latest"

# --- Utilities ---
"github:microsoft/apm" = "latest"
"npm:ccusage" = "latest"

[settings]
minimum_release_age = "3d"

[settings.npm]
package_manager = "pnpm"
