name: Set Up Python and Poetry
description: Set up specified Python version and install Poetry by using pipx

inputs:
  python-version:
    description: The version of Python to set up
    required: true

runs:
  using: composite
  steps:
    - name: Set Up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      run: |
        pip install --user pipx
        pipx ensurepath

        pipx install poetry
      shell: bash
