# local bin
export PATH="$HOME/.local/bin:$PATH"

# setup anyenv if it exists
if [ -d "$HOME/.anyenv" ]; then
    export ANYENV_ROOT="$HOME/.anyenv"
    export PATH="$ANYENV_ROOT/bin:$PATH"

    eval "$(anyenv init -)"
fi

# load other scripts
ZSHENV_DIR="$HOME/.zsh/env"

if [[ ! -z "$(ls $ZSHENV_DIR)" ]]; then
    for env_file in $ZSHENV_DIR/*; do
        source $env_file
    done
fi
