# enable autocomplete
autoload -Uz compinit && compinit

# load other scripts
ZSHRC_DIR="$HOME/.zsh/rc"

if [[ ! -z "$(ls $ZSHRC_DIR)" ]]; then
    for rc_file in $ZSHRC_DIR/*; do
        source $rc_file
    done
fi
